apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: cursodevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cursodevops
  template:
    metadata:
      labels:
        app: service-aforo255
    spec:
      containers:
      - name: cursodevops
        image: abocanegrab/cursodevops:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: cursodevops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
